# Lab 03: Fun with `pandas`!

Below are some exercises to get you working with `pandas` to manipulate data. As always, get as far as you can, and ask for help when you need it! Your teacher (me), you instructor, and your classmates are all here to help each other get better at coding. Getting the code to work is important, but do also take the time to make sure you understand what the commands are doing. This time, (with the exception of the Stroop challenge), all I've given you is the code to download the data. Then you are on your own. For the Stroop challenge, I gave the you code for the first step—after that, it's up to you :-)

## Music sales challenge

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Adds a column which marks whether each row is from the list of physical singles or digital singles
3. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
4. Outputs the artist and single name for the year you were 15 years old.

In [4]:
# Starter code...

%pip install lxml
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_best-selling_singles")

Requirement already satisfied: lxml in /opt/conda/lib/python3.10/site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
df_physical = rawdata[0]
df_physical['Media'] = "Physical"
df_physical

,Artist,Single,Released,Sales (in millions),Source,Media
0,Bing Crosby,"""White Christmas""",1942,50,[1],Physical
1,Elton John,"""Something About the Way You Look Tonight""/""Ca...",1997,33,[1],Physical
2,Bing Crosby,"""Silent Night""",1935,30,[2],Physical
3,Tino Rossi,"""Petit Papa Noël""",1946,30,[3],Physical
4,Bill Haley & His Comets,"""Rock Around the Clock""",1954,25,[4][5],Physical
5,Whitney Houston,"""I Will Always Love You""",1992,24,[6],Physical
6,Elvis Presley,"""It's Now or Never""",1960,20,[7][8],Physical
7,USA for Africa,"""We Are the World""",1985,20,[9],Physical
8,The Ink Spots,"""If I Didn't Care""",1939,19[disputed – discuss],[10],Physical
9,Celine Dion,"""My Heart Will Go On""",1997,18,[11],Physical
10,Mariah Carey,"""All I Want For Christmas Is You""",1994,16,[12],Physical
11,Baccara,"""Yes Sir, I Can Boogie""",1977,16,[13],Physical
12,Bryan Adams,"""(Everything I Do) I Do It for You""",1991,15,[14],Physical
13,John Travolta and Olivia Newton-John,"""You're the One That I Want""",1978,15,[15],Physical

In [6]:
df_digital = rawdata[3]
df_digital['Media'] = "Digital"
df_digital

,Artist,Single,Released,Sales (in millions),Source,Media
0,Ed Sheeran,"""Shape of You""",2017,41.5[a],[46][47],Digital
1,Luis Fonsi featuring Daddy Yankee,"""Despacito""",2017,36.1[a],[46][47],Digital
2,Rihanna featuring Drake,"""Work""",2016,32.5[a],[48],Digital
3,The Chainsmokers and Coldplay,"""Something Just Like This""",2017,21.5[a],[46][47],Digital
4,Ed Sheeran,"""Perfect""",2017,21.4[a],[46][47],Digital
5,Wiz Khalifa featuring Charlie Puth,"""See You Again""",2015,20.9[a],[49],Digital
6,The Chainsmokers featuring Halsey,"""Closer""",2016,20.7[a],[50][46],Digital
7,Adele,"""Rolling in the Deep""",2011,20.6,[51][52][53],Digital
8,Mark Ronson featuring Bruno Mars,"""Uptown Funk""",2015,20[a],[49],Digital
9,Billie Eilish,"""Bad Guy""",2019,19.5[a],[54],Digital
10,Ed Sheeran,"""Thinking Out Loud""",2015,19.5[a],[49],Digital
11,Camila Cabello featuring Young Thug,"""Havana""",2017,19.0[a],[46][47],Digital
12,Lil Nas X,"""Old Town Road""",2018,18.4[a],[54],Digital
13,Carly Rae Jepsen,"""Call Me Maybe""",2011,18.0,[55],Digital
14,Taylor Swift,"""Love Story""",2008,18.0[a],[56],Digital
15,Adele,"""Someone Like You""",2011,17.0,[57],Digital
16,Rihanna,"""Needed Me""",2016,17.0[a],[48],Digital
17,Shawn Mendes and Camila Cabello,"""Señorita""",2019,16.1[a],[54],Digital
18,Imagine Dragons,"""Radioactive""",2012,16[a],[58],Digital
19,Imagine Dragons,"""Believer""",2017,15.4[a],[59][60],Digital
20,Drake,"""God's Plan""",2018,15.3[a],[47],Digital

In [7]:
df_combined = pd.concat([df_physical, df_digital])
df_combined

,Artist,Single,Released,Sales (in millions),Source,Media
0,Bing Crosby,"""White Christmas""",1942,50,[1],Physical
1,Elton John,"""Something About the Way You Look Tonight""/""Ca...",1997,33,[1],Physical
2,Bing Crosby,"""Silent Night""",1935,30,[2],Physical
3,Tino Rossi,"""Petit Papa Noël""",1946,30,[3],Physical
4,Bill Haley & His Comets,"""Rock Around the Clock""",1954,25,[4][5],Physical
5,Whitney Houston,"""I Will Always Love You""",1992,24,[6],Physical
6,Elvis Presley,"""It's Now or Never""",1960,20,[7][8],Physical
7,USA for Africa,"""We Are the World""",1985,20,[9],Physical
8,The Ink Spots,"""If I Didn't Care""",1939,19[disputed – discuss],[10],Physical
9,Celine Dion,"""My Heart Will Go On""",1997,18,[11],Physical
10,Mariah Carey,"""All I Want For Christmas Is You""",1994,16,[12],Physical
11,Baccara,"""Yes Sir, I Can Boogie""",1977,16,[13],Physical
12,Bryan Adams,"""(Everything I Do) I Do It for You""",1991,15,[14],Physical
13,John Travolta and Olivia Newton-John,"""You're the One That I Want""",1978,15,[15],Physical
0,Ed Sheeran,"""Shape of You""",2017,41.5[a],[46][47],Digital
1,Luis Fonsi featuring Daddy Yankee,"""Despacito""",2017,36.1[a],[46][47],Digital
2,Rihanna featuring Drake,"""Work""",2016,32.5[a],[48],Digital
3,The Chainsmokers and Coldplay,"""Something Just Like This""",2017,21.5[a],[46][47],Digital
4,Ed Sheeran,"""Perfect""",2017,21.4[a],[46][47],Digital
5,Wiz Khalifa featuring Charlie Puth,"""See You Again""",2015,20.9[a],[49],Digital
6,The Chainsmokers featuring Halsey,"""Closer""",2016,20.7[a],[50][46],Digital
7,Adele,"""Rolling in the Deep""",2011,20.6,[51][52][53],Digital
8,Mark Ronson featuring Bruno Mars,"""Uptown Funk""",2015,20[a],[49],Digital
9,Billie Eilish,"""Bad Guy""",2019,19.5[a],[54],Digital
10,Ed Sheeran,"""Thinking Out Loud""",2015,19.5[a],[49],Digital
11,Camila Cabello featuring Young Thug,"""Havana""",2017,19.0[a],[46][47],Digital
12,Lil Nas X,"""Old Town Road""",2018,18.4[a],[54],Digital
13,Carly Rae Jepsen,"""Call Me Maybe""",2011,18.0,[55],Digital
14,Taylor Swift,"""Love Story""",2008,18.0[a],[56],Digital
15,Adele,"""Someone Like You""",2011,17.0,[57],Digital
16,Rihanna,"""Needed Me""",2016,17.0[a],[48],Digital
17,Shawn Mendes and Camila Cabello,"""Señorita""",2019,16.1[a],[54],Digital
18,Imagine Dragons,"""Radioactive""",2012,16[a],[58],Digital
19,Imagine Dragons,"""Believer""",2017,15.4[a],[59][60],Digital
20,Drake,"""God's Plan""",2018,15.3[a],[47],Digital

In [41]:
a = list(df_combined['Artist'])
a

['Bing Crosby',
 'Elton John',
 'Bing Crosby',
 'Tino Rossi',
 'Bill Haley & His Comets',
 'Whitney Houston',
 'Elvis Presley',
 'USA for Africa',
 'The Ink Spots',
 'Celine Dion',
 'Mariah Carey',
 'Baccara',
 'Bryan Adams',
 'John Travolta and Olivia Newton-John',
 'Ed Sheeran',
 'Luis Fonsi featuring Daddy Yankee',
 'Rihanna featuring Drake',
 'The Chainsmokers and Coldplay',
 'Ed Sheeran',
 'Wiz Khalifa featuring Charlie Puth',
 'The Chainsmokers featuring Halsey',
 'Adele',
 'Mark Ronson featuring Bruno Mars',
 'Billie Eilish',
 'Ed Sheeran',
 'Camila Cabello featuring Young Thug',
 'Lil Nas X',
 'Carly Rae Jepsen',
 'Taylor Swift',
 'Adele',
 'Rihanna',
 'Shawn Mendes and Camila Cabello',
 'Imagine Dragons',
 'Imagine Dragons',
 'Drake']

In [43]:
b = list(df_combined['Single'])
b

['"White Christmas"',
 '"Something About the Way You Look Tonight"/"Candle in the Wind 1997"',
 '"Silent Night"',
 '"Petit Papa Noël"',
 '"Rock Around the Clock"',
 '"I Will Always Love You"',
 '"It\'s Now or Never"',
 '"We Are the World"',
 '"If I Didn\'t Care"',
 '"My Heart Will Go On"',
 '"All I Want For Christmas Is You"',
 '"Yes Sir, I Can Boogie"',
 '"(Everything I Do) I Do It for You"',
 '"You\'re the One That I Want"',
 '"Shape of You"',
 '"Despacito"',
 '"Work"',
 '"Something Just Like This"',
 '"Perfect"',
 '"See You Again"',
 '"Closer"',
 '"Rolling in the Deep"',
 '"Uptown Funk"',
 '"Bad Guy"',
 '"Thinking Out Loud"',
 '"Havana"',
 '"Old Town Road"',
 '"Call Me Maybe"',
 '"Love Story"',
 '"Someone Like You"',
 '"Needed Me"',
 '"Señorita"',
 '"Radioactive"',
 '"Believer"',
 '"God\'s Plan"']

In [46]:
c = list(df_combined['Released'])
c

[1942,
 1997,
 1935,
 1946,
 1954,
 1992,
 1960,
 1985,
 1939,
 1997,
 1994,
 1977,
 1991,
 1978,
 2017,
 2017,
 2016,
 2017,
 2017,
 2015,
 2016,
 2011,
 2015,
 2019,
 2015,
 2017,
 2018,
 2011,
 2008,
 2011,
 2016,
 2019,
 2012,
 2017,
 2018]

In [49]:
d = list(zip(a, b, c))
d

[('Bing Crosby', '"White Christmas"', 1942),
 ('Elton John',
  '"Something About the Way You Look Tonight"/"Candle in the Wind 1997"',
  1997),
 ('Bing Crosby', '"Silent Night"', 1935),
 ('Tino Rossi', '"Petit Papa Noël"', 1946),
 ('Bill Haley & His Comets', '"Rock Around the Clock"', 1954),
 ('Whitney Houston', '"I Will Always Love You"', 1992),
 ('Elvis Presley', '"It\'s Now or Never"', 1960),
 ('USA for Africa', '"We Are the World"', 1985),
 ('The Ink Spots', '"If I Didn\'t Care"', 1939),
 ('Celine Dion', '"My Heart Will Go On"', 1997),
 ('Mariah Carey', '"All I Want For Christmas Is You"', 1994),
 ('Baccara', '"Yes Sir, I Can Boogie"', 1977),
 ('Bryan Adams', '"(Everything I Do) I Do It for You"', 1991),
 ('John Travolta and Olivia Newton-John',
  '"You\'re the One That I Want"',
  1978),
 ('Ed Sheeran', '"Shape of You"', 2017),
 ('Luis Fonsi featuring Daddy Yankee', '"Despacito"', 2017),
 ('Rihanna featuring Drake', '"Work"', 2016),
 ('The Chainsmokers and Coldplay', '"Something Just Like This"', 2017),
 ('Ed Sheeran', '"Perfect"', 2017),
 ('Wiz Khalifa featuring Charlie Puth', '"See You Again"', 2015),
 ('The Chainsmokers featuring Halsey', '"Closer"', 2016),
 ('Adele', '"Rolling in the Deep"', 2011),
 ('Mark Ronson featuring Bruno Mars', '"Uptown Funk"', 2015),
 ('Billie Eilish', '"Bad Guy"', 2019),
 ('Ed Sheeran', '"Thinking Out Loud"', 2015),
 ('Camila Cabello featuring Young Thug', '"Havana"', 2017),
 ('Lil Nas X', '"Old Town Road"', 2018),
 ('Carly Rae Jepsen', '"Call Me Maybe"', 2011),
 ('Taylor Swift', '"Love Story"', 2008),
 ('Adele', '"Someone Like You"', 2011),
 ('Rihanna', '"Needed Me"', 2016),
 ('Shawn Mendes and Camila Cabello', '"Señorita"', 2019),
 ('Imagine Dragons', '"Radioactive"', 2012),
 ('Imagine Dragons', '"Believer"', 2017),
 ('Drake', '"God\'s Plan"', 2018)]

In [70]:
d[28]

('Taylor Swift', '"Love Story"', 2008)

In [71]:
d[30]

('Rihanna', '"Needed Me"', 2016)

## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [74]:
# Starter code...

#%pip install lxml
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration")

In [85]:
missions0 = rawdata[0]
missions1 = rawdata[1]
missions2 = rawdata[2]
missions3 = rawdata[3]
missions4 = rawdata[4]
missions5 = rawdata[5]
missions6 = rawdata[6]
missions7 = rawdata[7]
df_combi = pd.concat([missions0, missions1, missions2, missions3, missions4, missions5, missions6, missions7])
df_combi

,Mission name,Launch date,Description,Ref(s)
0,Sputnik 1,4 October 1957,First Earth orbiter,[1][2]
1,Sputnik 2,3 November 1957,"Earth orbiter, first animal in orbit, a dog na...",[2][3][4]
2,Explorer 1,1 February 1958,Earth orbiter; discovered Van Allen radiation ...,[5]
3,Vanguard 1,17 March 1958,Earth orbiter; oldest spacecraft still in Eart...,[6]
4,Luna 1,2 January 1959,First lunar flyby (attempted lunar impact?); f...,[7][8][9][10]
...,...,...,...,...
18,Peregrine Mission One (including Iris and Colm...,8 January 2024,Lunar lander and rovers (landing precluded),[504]
19,IM-1 Nova-C Odysseus (including EagleCam deplo...,15 February 2024,Lunar landers,[505]
20,DRO A/B,13 March 2024,Lunar orbiters,[506]
21,Queqiao-2 (including Tiandu-1 and 2),20 March 2024,Lunar orbiters,[507]
22,Chang'e 6 (including Pakistan's ICUBE-Q cubesat),3 May 2024,"Lunar sample return, rover and orbiters; first...",[508][509]

In [92]:
space = df_combi['Launch date']
space

0       4 October 1957
1      3 November 1957
2      1 February 1958
3        17 March 1958
4       2 January 1959
            ...
18      8 January 2024
19    15 February 2024
20       13 March 2024
21       20 March 2024
22          3 May 2024
Name: Launch date, Length: 233, dtype: object

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [96]:
rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")
debut0 = rawdata[0]
debut1 = rawdata[1]
debut2 = rawdata[2]
debut3 = rawdata[3]
debut4 = rawdata[4]
debut5 = rawdata[5]
debut6 = rawdata[6]
debut7 = rawdata[7]
debut8 = rawdata[8]
dfcomb = pd.concat([debut0, debut1, debut2, debut3, debut4, debut5, debut6, debut7, debut8])
dfcomb

,0,1,Character / Team,Year Debuted,Company,Creator/s,First Appearance
0,NaN,This article has multiple issues. Please help ...,NaN,NaN,NaN,NaN,NaN
1,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
2,NaN,This article needs additional citations for ve...,NaN,NaN,NaN,NaN,NaN
0,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
0,NaN,This article needs additional citations for ve...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
87,NaN,NaN,Crossbones,1989,Marvel,"Mark Gruenwald, Kieron Dwyer",Captain America #360
88,NaN,NaN,Mud Pack,1989,DC,NaN,Detective Comics #604
89,NaN,NaN,Artemiz,1989,DC,John Ostrander,Suicide Squad #35
90,NaN,NaN,Anarky,1989,DC,"Alan Grant, Norm Breyfogle",Detective Comics #608
91,NaN,NaN,Assembly of Evil,1989,Marvel,NaN,Acts of Vengeance

## Stroop challenge

Every year between 2015 and 2021, the students in my Language, Cognition, and the Brain course participated in a version of the Stroop task. Using a stopwatch (ok, using their phones), they recorded how fast they could say a list of things (either reading or naming colors or color words). The column names mean "Reading with No Interference", "Naming with Interference", "Naming with No Interference", and "Reading with Interference". The times are in seconds.

### Stroop challenge 1: 
Transform these data from wide format to long format, so that the result is a dataframe with
- 1 column named "Participant_id" with a unique number for each participant (you can use the row indices)
- 1 column named "Year" with the year data
- 1 column named "Task" that shows which task they were doing
- 1 column named "RT" that shows their response time

In [ ]:
# Starter code 1...

df = pd.read_csv("https://raw.githubusercontent.com/ethanweed/Stroop/master/Stroop-raw-over-the-years.csv")
df.head()

In [ ]:
# Starter code 2...

# Make a new column using the dataframe indices as particpant numbers

df.index.name = 'Participant_id'
df = df.reset_index()

#df.reset_index(inplace = True)
# NOTE: This line does exactly the same thing as the line above:
# it replaces the original df with a new df with the updated index. That's what
# "inplace = True" means. Or, you can just assign the dataframe with the updated index
# to a new dataframe with the same name as the old dataframe, which is what I did above.
# The end result is the same.

df

## Stroop challenge 2 (Advanced!!!):

Make a new dataframe which shows the mean response time (in seconds) for each task for each year.